### ISSUE TITLE
Set up upload Gradle Plugin Portal

### ISSUE THREAD

**Issue by wzieba** [Automattic/measure-builds-gradle-plugin#42]
In the past, this plugin was hosted on Gradle Plugin Portal. We changed it to Automattic's S3 instance though to get more features (per commit publish).

But when #38 will be merged, it'll make sense to offer the plugin on Gradle Plugin Portal as well, to make it available for a wider audience, that prefer to use a standardized repository (Gradle Plugin Portal) than custom, 3rd party one (Automattic's S3).

**Comment by takahirom** [comment]
@wzieba Do you have any plans for this? I would like to share this plugin with others.

**Comment by wzieba** [comment]
We're waiting for approval from Gradle Plugin Portal: https://github.com/Automattic/measure-builds-gradle-plugin/actions/runs/8480293061/job/23235774694#step:4:30

**Comment by wzieba** [comment]
hi there @takahirom ! I just got information from Gradle Plugin Portal that plugin submission for the plugin was rejected due to a need of proving automattic.com domain. I'm working on it 👍

**Comment by wzieba** [comment]
👋 @takahirom ! We added verification records and I've sent the plugin for verification again https://github.com/Automattic/measure-builds-gradle-plugin/actions/runs/8480293061/job/23443593754#step:4:24

**Comment by wzieba** [comment]
@takahirom the plugin is now available on Gradle Plugin Portal: https://plugins.gradle.org/plugin/com.automattic.android.measure-builds

**Comment by takahirom** [comment]
Thank you for letting me know! I'll try it out shortly.

**Comment by takahirom** [comment]
It works wonderfully! Thank you for your effort!
